### ISSUE TITLE
Overwriting config files

### ISSUE THREAD

**Issue by smathev** [hotio/docker-suitarr#1]
Hi.

I've been using the Linuxserver build of sonarr and radarr, but I much prefer the idea of using more frequently released (and updated) containers... I really like your idea, and I wanted to test it, unfortunately the docker-file seems to overwrite the default ports and use post 8080 - furthermore it actually seems to delete my existing config file in the specified config-location. 

This means I can't use you're software since I depend on an vpn-client and a nginx reverse-proxy fron dperson (dperson/nginx and dperson/openvpn-client here on github).

Is there any way you could have your dockerfile check for existing config-files in the -v config-file argument, instead of just overwriting it?

I can elaborate if my question is unclear .... Thanks in advance!

**Comment by hotio** [comment]
It shouldn't overwrite config files, if a file is found it should update the port to 8080.

```
if [[ $APP == "radarr" ]] || [[ $APP == "sonarr" ]]; then
    [[ -f /config/nzbdrone.pid ]] && rm /config/nzbdrone.pid

    if [[ -f /config/config.xml ]]; then
        sed -i 's/<Port>.*<\/Port>/<Port>8080<\/Port>/g' /config/config.xml
    else
        echo '<Config><Port>8080</Port></Config>' > /config/config.xml
    fi
fi
```

**Comment by smathev** [comment]
I see :) 
That makes sense.

I'm no Linux wiz, so I'm sorta figuring this out as I go ... 

I have an issue of using a docker-compose file, which I can't quite make the suitar builds work with. They end up in an "unhealthy" state, and I can't enter the container with docker exec.

Is there anyway to mitigate that issue?

**Comment by smathev** [comment]
... Sorry, you shouldn't spend time fixing my issues.

I guess I have a sorta special setup.

I run an openvpn-client, which I force specific dockers to use (sonarr, radarr, and deluge). I then use nginx for local port-forwards so I can access those sites locally. It's all build using a docker-compose file, and I wanted to switch from the linuxserver-builds of radarr and sonarr to your versions, but I can't quite make it work.

If you're up for helping me I would appreciate it, but if that's beyond the point of your suitarr build and everything I understand :)

**Comment by hotio** [comment]
Could you show the docker compose?

**Comment by smathev** [comment]
Sure - do you want it all, or just the relevant parts?

The specific parts are that I use are dperson/openvpn to make sure that the dockers are routed through vpn and dperson/nginx to make sure that dockers are available on the localnetwork. This all works when using the linuxserver dockers.

The Sonarr and Radarr specific parts that I use from linuxserver are:
   sonarr:
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: always
        network_mode: 
            "service:nordvpn-client"
        environment:
            - PUID=1000 
            - PGID=1000 
        volumes:


    radarr:
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: always
        network_mode: 
            "service:nordvpn-client"
        environment:
            - PUID=1000 
            - PGID=1000 
        volumes:

and I wrote the suitarr parts like this:
sonarr:
        container_name: sonarr
        image: hotio/suitarr:latest
        restart: always
        network_mode: 
            "service:nordvpn-client"
        environment:
            - APP=sonarr 
            - PUID=1000 
            - PGID=1000 
            - UMASK=022
            - VERSION=stable 
        volumes:


    radarr:
        container_name: radarr
        image: hotio/suitarr:latest
        restart: always
        network_mode: 
            "service:nordvpn-client"
        environment:
            - APP=radarr 
            - PUID=1000 
            - PGID=1000 
            - UMASK=022
            - VERSION=stable 
        volumes:


This is again the most relevant parts .... I ofc have added volumes to both of them, and the config-file location is one of them.

**Comment by hotio** [comment]
This does not clear anything up for me.

What happens when you start with a clean install of radarr, so no config file. Is the nginx capable of finding the radarr instance on port 8080, and are you able to connect to it? I have no knowledge about the vpn part... perhaps we could try without that for now.

**Comment by smathev** [comment]
So ... I fixed the problem with the Linuxserver-docker, it was because docker-compose prefers local images - which I didn't know, so my original reason for wanting to try your build has actually fixed itself ... But I returned to troubleshooting my issues with suitarr, and I managed to fix the Sonarr one ... It was my own fault, for not being attentive when changing paths, etc. 

However, the radarr-part is still causing trouble - at least when I use the docker-compose file (I haven't tried it in a pure "docker run ..." - anyway, when I check the radarr-containers log (built through the suitarr file) it reads:
"
usermod: no changes
[cont-init.d] 00-setup-environment: exited 0.
[cont-init.d] 10-install-app: executing...
[cont-init.d] 10-install-app: exited 0.
[cont-init.d] 11-setup-config: executing...
[cont-init.d] 11-setup-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.


Press enter to exit...
"

So, I'm guessing it needs my user-input to be done with creating the images - and that's the reason why I can't get it up and running right now :/

Do you have any suggestions?


PS. Like I said - my original issue has been fixed (and I now run the latests updated images from Linuxserver), so if you don't feel like troubleshooting further it's fine by me, but if you do want to figure this out I'd be happy to continue the troubleshooting :D

**Comment by hotio** [comment]
Press enter to exit, usually means that radarr or something else fails to start, if logs are created, you could check why radarr fails.

**Comment by smathev** [comment]
Ok, I'll look into it at some point ... Thanks for getting back to me 😄
