### ISSUE TITLE
no instructions to /movies or /downloaded folder?

### ISSUE THREAD

**Issue by Panderine** [hotio/docker-suitarr#2]
I'm testing your img, is there a reason not to put those on the documentation?.
Also, it doesn't mention the "-d" parameter so when you run it, it is in interactive mode an attached to tty.
Lastly, if the host server is restarted the container is lost ("--rm").

I'm very new to docker. Can you recommend the correct way to run this container in a "set it and forget it" way?.

Thanks!!

**Comment by hotio** [comment]
I'm only listing the volumes required to get the container running, I'm assuming that people know "a bit" when running docker containers and should be able to figure this one out themselves.

`-d` is not required and if somebody not familiar with docker executes the command, the most stupid thing according to me is to erase from the screen that anything is going on...

Running with `--rm` should have no downsides, if it does, you are doing it wrong.

In short the sample commands are an ideal starting point when running from systemd. If the commands are executed just from the commandline, they should spin up the container with minimal customization to the command and the least amount of impact after it closes when doing ctrl-c. Afterwards the same command can easily be run again, without knowing how to clean up old containers.

In really short, they are the defaults and bare minimum to get the container started.

Does that answer anything? Sorry your question went unanwered for 4 days, forget to watch my own repo.

**Comment by Panderine** [comment]
Thanks hotio. Yes it's clear. I'm starting with docker myself. I think this is just another approach since you are managing the docker/services within systemd. I use a restart policy for each and run them with -d. Also I check logs from CLI or using portainer.  So I was trying to fit my understanding with your instructions and it didn't make sense to me. I realise why now :)

How do you manage application upgrade?. I believe the in-app update mechanism shouldn't be use, instead a new docker image should be downloaded and docker regenerated. How do you manage that without manual intervention?

**Comment by hotio** [comment]
Well, suitarr updates/installs a fresh version of the app every time the container is started. So the app gets updated by just restarting the container. To update the image, I just do a docker pull in the systemd unit file before starting the container. All I have to do is `sudo systemctl restart docker-radarr` and voila, the updated image is pulled, new container is started and app is up2date. So logicaly doing a `sudo reboot` or when I'm standing next to the server, all it takes is a press or two on the button and all is updated.

**Comment by Panderine** [comment]
Problem is my servers is 24/7 up, so maybe I should put a restart in cron
for those containers. Thanks!
