### ISSUE TITLE
change net node to access services "outside" of the docker?

### ISSUE THREAD

**Issue by zeflash** [hotio/docker-suitarr#3]
Hey, thanks for your awesome image, I'm planning on using those in the short future to replace all my currently running services (I'm on a QNAP).

I'm test driving Radarr, and wanted to test out importing off CouchPotato which runs on the host. The container doesn't seem to be able to access the host IP. I remember having those issues on other dockers in the past, solution being to add "--net host".

Given you provide an image that include multiple services, I was wondering how you dealt with it yourself? For example, how would I access one NZBIndex container from a Radarr container?

Thanks for your work and your help!

**Comment by hotio** [comment]
When using bridge network, if your container is called nzbget, you can reach nzbget from radarr with nzbget:6789 if they are on the same bridge network

**Comment by zeflash** [comment]
great thanks, I didn't know that.
For services running on the host and not in containers though, I assume the only solution is to have the container running with --net host?

Any adverse consequence in having all the containers sharing the host net layer? Provided I make sure all ports are different?

**Comment by hotio** [comment]
I think it is best to start reading up on docker and how it works...

If you wanna run on the bridge or host network is a personal preference.
