### ISSUE TITLE
Radarr: --port doesn't overwrite the value saved in config.xml

### ISSUE THREAD

**Issue by zeflash** [hotio/docker-suitarr#4]
I noticed you changed the doc in order to include a port value when running the container. It wasn't working for me, until I understood why: I had the port already set to 8080 in config.xml.

Given we reuse the config file, it stays as it is (saw a closed issue about this). So it will only work when first creating the config file. 

Not sure if you can overwrite something there, but I think it's worth mentioning!

**Comment by hotio** [comment]
At first I ran all apps on port 8080, when starting the containers I updated the configs if needed. However it was not possible to run on the host network.

As of know no ports are exposed in the Dockerfile, so you should map them when using bridge `-p 7878:7878` or `--expose` when running on host network.
