### ISSUE TITLE
Lidarr not working on Synology

### ISSUE THREAD

**Issue by kleagon** [hotio/docker-suitarr#6]
All other apps are working fine, however, I have been unable to start Lidarr, I keep receiving the following error:

`Cannot open assembly '/app/Lidarr.exe': No such file or directory.`

This is on DMS 6+.

**Comment by hotio** [comment]
Did you use the "unstable" version of Lidarr?

**Comment by vertigo235** [comment]
Yes you need to use the unstable tag

**Comment by joshnat** [comment]
I'm getting the same error on Ubuntu 17.10, with VERSION=unstable for Lidarr

**Comment by hotio** [comment]
I'm unable to replicate this issue. Lidarr is installed and started just fine when running with `VERSION=unstable`
