### ISSUE TITLE
Cannot open assembly '/app/Lidarr.exe': No such file or directory.

### ISSUE THREAD

**Issue by hexleyOlive** [hotio/docker-suitarr#7]
After start the docker with Lidarr (with default values), an error is visible in log every second and Linarr web interface is not available : 
Cannot open assembly '/app/Lidarr.exe': No such file or directory.

Run docker with Sonarr, Radarr and Jackett is ok (with default values)

**Comment by hotio** [comment]
Use unstable version for Lidarr, Lidarr doesn't build binaries for their stable branch IIRC, their stable is too unstable, so therefor you should use unstable to get something stable...Makes sense? :-)
